version: '3'
services:
  # Container Name and its configuration
  api-service:
    image: alji
    ports:
      -8080:8080

  auth-service:
    image: auth
    ports:
      -8081:8081
    environment:
      - KC_USER_NAME=admin